### ISSUE TITLE
Few bugs after implementing

### ISSUE THREAD

**Issue by CLTanuki** [juangburgos/QCrashHandler#1]
First, ```./qcrashdumper: line 108: ${curr_line}: ambiguous redirect```:
${curr_line} should be put in the braces.
And links in .h files are sometimes broken.
You can test it, if You will clone the repository and try to build.

BTW, thanks for library!

**Comment by juangburgos** [comment]
Hi, thanks for the feedback. Could you please expand a little on the issues?

Line `108` on `qcrashdumper` points to an [empty line](https://github.com/juangburgos/QCrashHandler/blob/d4bf88655880f1656916799defb5740027e533c1/src/qcrashdumper#L108). So I don't know where exactly is `${curr_line}` supposed to be in braces.

Also what do you mean with *links in .h files are sometimes broken* ? Could you post some compiler output to see where exactly this fails?

I build on Windows and CentOS7 and so far have not found issues like the ones you report. Where are you building on?

**Comment by CLTanuki** [comment]
After cloning to subfolder (there's one special subfolder for modules):
![image](https://user-images.githubusercontent.com/5824716/72205127-951f1a80-3490-11ea-8365-8c3df9113480.png)

**Comment by juangburgos** [comment]
Probably you forgot to clone recursively
